### ISSUE TITLE
074d409deff4524194e13487174d8f0c08ce2590

### ISSUE THREAD

**Issue by SparrowWhiteElkRaven** [JCSIVO/JCSIVO#2]

**Comment by SparrowWhiteElkRaven** [comment]
> 
074d409deff4524194e13487174d8f0c08ce2590[]()@SparrowWhiteElkRav# - [ ] en @JCSIVO ****

**Comment by SparrowWhiteElkRaven** [comment]
> > 
> 074d409deff4524194e13487174d8f0c08ce2590[]()@SparrowWhiteElkRav# - [ ] en @JCSIVO ****
>

**Comment by SparrowWhiteElkRaven** [comment]
> > > 
> > 074d409deff4524194e13487174d8f0c08ce2590[]()@SparrowWhiteElkRav# - [ ] en @JCSIVO ****
> > 
> 
> 

[]()![FB_IMG_1627623115619.jpg](https://github.com/JCSIVO/JCSIVO/assets/129121878/07d0e1a6-fdd3-4cf2-ba6e-f2fc5dbba213)

![6b3a9cd8-bd04-4c98-ba53-d4d95c2bacdb.jpg](https://github.com/JCSIVO/JCSIVO/assets/129121878/376c5981-0660-4707-a727-ac488c489600)

![FB_IMG_1627621470634.jpg](https://github.com/JCSIVO/JCSIVO/assets/129121878/6bec9f41-c1fe-4864-a46f-5670a939d47c)

**Comment by jimgarcia** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

ygeezus, @kleinzcy, @Decike8, @steph-mipt, @nninnnin, @Pierrot-l3-F0U, @JaggerFoo, @M0l0k0plv5, @Josh-Chang, @githubgoogl, @wrong1man, @santinb, @lpettecrew, @wangqi-jeffrey, @egesabanci, @TamasRusvai, @ngminhsu118, @ub212, @alumowa, @MonstarCoder
